---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: GroupPolicyAttachment
metadata:
  name: sample-grouppolicyattachment
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        some-group: attach
    groupNameRef:
      name: somegroup
  providerConfigRef:
    name: example
